name: Needs

on: 
  push:
    branches:
      - needs

jobs:
  distribute:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.distribute.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - name: distribute
        id: distribute
        run: echo '::set-output name=result::[]'
      - name: echo output
        run: echo ${{steps.distribute.outputs.result}}

  job-1:
    runs-on: ubuntu-latest
    needs: [distribute]
    if: contains(needs.distribute.outputs.targets, 'job-1')
    outputs:
      message: ${{ steps.message.outputs.result }}
    steps:
      - name: echo 
        id: message
        run: echo '::set-output name=result::job-1 complete'
  
  job-2:
    runs-on: ubuntu-latest
    needs: [distribute]
    if: contains(needs.distribute.outputs.targets, 'job-2')
    outputs:
      message: ${{ steps.message.outputs.result }}
    steps:
      - name: echo 
        id: message
        run: echo '::set-output name=result::job-2 complete'

  
  job-3:
    runs-on: ubuntu-latest
    needs: [distribute]
    if: contains(needs.distribute.outputs.targets, 'job-3')
    outputs:
      message: ${{ steps.message.outputs.result }}
    steps:
      - name: echo 
        id: message
        run: echo '::set-output name=result::job-3 complete'


  complete:
    runs-on: ubuntu-latest
    needs: [job-1, job-2, job-3]
    if: failure() != true
    steps:
      - name: echo
        run: |
          echo '${{needs.job-1.outputs.message}}'
          echo '${{needs.job-2.outputs.message}}'
          echo '${{needs.job-3.outputs.message}}'